//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY
    {
        public string SecurityID { get; set; }
        public string OwnUN { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    
        public virtual PEOPLE Person { get; set; }
    }
}
