//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_MANAGER
    {
        public string TicketManagerID { get; set; }
        public int TrainID { get; set; }
        public int TotalTickets { get; set; }
        public int BookedTickets { get; set; }
    
        public virtual TRAIN TRAIN { get; set; }
    }
}
