//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRIP()
        {
            this.TICKETs = new HashSet<TICKET>();
        }
    
        public int ScheduleID { get; set; }
        public int TrainID { get; set; }
        public decimal BasicPrice { get; set; }
        public string DriverUN { get; set; }
    
        public virtual PEOPLE Person { get; set; }
        public virtual SCHEDULE SCHEDULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKETs { get; set; }
        public virtual TRAIN TRAIN { get; set; }
    }
}
